#!/usr/bin/perl

my %vars;

while( <> )
{
    next if( /^\#/ || /^\s*$/ || ! /\=/ );
    /([^=]+)=(.*)/;
    $vars{$1} = $2;
}

$vars{''} = "%";

while( <STDIN> )
{
    s/%(\w+)%/${\(getvar( $1 ))}/g;
    print;
}

sub getvar()
{
    my( $key ) = @_;
    if( exists( $vars{$key} ))
    {
        return $vars{$key}
    }
    if( exists( $ENV{$key} ))
    {
        return $ENV{$key}
    }
    die "Unknown configuration variable: $key\n";
}
