#!/usr/bin/perl

my %vars;

foreach my $key (keys %ENV)
{
    $vars{$key} = $ENV{$key};
}

while( <> )
{
    next if( /^\#/ || /^\s*$/ || ! /\=/ );
    /([^=]+)=(.*)/;
    $vars{$1} = $2;
}

$vars{''} = "%";

while( <STDIN> )
{
    s/%(\w+)%/$vars{$1}/g;
    print;
}
