#!/bin/sh

# Get base directory

dir="`realpath "$0"`"
dir="`dirname "$dir"`"
dir="`dirname "$dir"`"

cd "$dir"

export BASEDIR="$dir"

# Fix this if it isn't already :P
chmod o-rw configs/passwd*

# Make this if necessary
mkdir -p log

start() {
    if [ ! -e configs/icecast.xml ]; then
        # Not providing our own icecast server
        true
    elif checkicecast; then
        echo "Icecast already running"
    else
        echo "Starting Icecast..."
        iccfg="`mktemp --suff .xml /tmp/icecast.XXXXXXXX`"
        tools/cfgtemplate configs/*.cfg < configs/icecast.xml >> "$iccfg"
        icecast -b -c "$iccfg" >> log/icecast.log 2>&1
        # icpid=$!
        # sleep 3
        # echo $icpid > configs/icecast.pid
    fi

    if checkezstream; then
        echo "EZStream already running"
    else
        echo "Starting EZStream..."
        ezcfg="`mktemp --suff .xml /tmp/ezstream.XXXXXXXX`"
        tools/cfgtemplate configs/*.cfg < configs/ezstream.xml >> "$ezcfg"

        ezstream -c "$ezcfg" >> log/ezstream.log 2>&1 & disown
        ezpid=$!

        echo $ezpid > configs/ezstream.pid
    fi
}

stop() {
    if checkezstream; then
        echo "Stopping EZStream..."
        /bin/kill --timeout 5000 KILL `cat configs/ezstream.pid`
    else
        echo "EZStream not running"
    fi

    if [ ! -e configs/icecast.xml ]; then
        # Not providing our own icecast server
        true
    elif checkicecast; then
        echo "Stopping Icecast..."
        /bin/kill --timeout 5000 KILL `cat configs/icecast.pid`
    else
        echo "Icecast not running"
    fi

    rm -f configs/icecast.pid configs/ezstream.pid
}

status() {
    response=2
    if [ ! -e configs/icecast.xml ]; then
        response=$(($response - 1))
    elif checkicecast; then
        echo "Icecast running"
        response=$(($response - 1))
    else
        echo "Icecst not running"
    fi

    if checkezstream; then
        echo "EZStream running"
        response=$(($response - 1))
    else
        echo "EZStream not running"
    fi

    return $response
}

checkicecast() {
    if [ ! -e configs/icecast.pid ]; then
        return 1
    fi
    icpid=`cat configs/icecast.pid`
    icname=`ps -p $icpid -o comm --no-headers`
    if [ "$icname" != "icecast" ]; then
        return 1
    fi

    return 0
}

checkezstream() {
    if [ ! -e configs/ezstream.pid ]; then
        return 1
    fi
    ezpid=`cat configs/ezstream.pid`
    ezname=`ps -p $ezpid -o comm --no-headers`
    if [ "$ezname" != "ezstream" ]; then
        return 1
    fi

    return 0
}

case $1 in
    ''|start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        ;;
    status)
        status
        ;;

    *)
        echo "Usage: $0 [start|stop|restart|status]"
        exit 1
        ;;

esac
