#!/bin/sh

TAG=radiouse
BASE=/media/sf_nathanr/Music/Album
TARGET=~/radiotest/library/music

find "$BASE" -iname "$TAG" | while read file; do
    file="`dirname "$file"`"
    dir="`dirname "$file"`"
    name="`basename "$file"`"
    if [ -e "$TARGET/$name" ]; then
        tpath="`realpath "$TARGET/$name"`"
        bpath="`realpath "$file"`"
        if [ "$tpath" = "$bpath" ]; then
            # Already exists, do nothing
            # echo "+ $file"
            true
        else
            # Already exists, but is something else
            alt="`dirname "$file"`"
            alt="`basename "$alt"` - $name"
            if [ ! -e "$TARGET/$alt" ]; then
                echo "$alt"
                ln -s "`realpath "$file"`" "$TARGET/$alt"
            fi
        fi
    else
        # Doesn't exist, link it
        echo "$name"
        ln -s "`realpath "$file"`" "$TARGET/$name"
    fi
done
