#!/bin/sh

# These settings can also be placed in configs/settings.sh

TAG=radiouse
BASE=/media/sf_nathanr/Music
TARGET=/srv/chill/library/music

# Get base directory

dir="`realpath "$0"`"
dir="`dirname "$dir"`"
dir="`dirname "$dir"`"

if [ -e "$dir/configs/settings.sh" ]; then
    . "$dir/configs/settings.sh"
fi

find "$BASE" -iname "$TAG" | while read file; do
    tag="$file"
    file="`dirname "$file"`"
    dir="`dirname "$file"`"
    name="`basename "$file"`"
    if [ -s "$tag" ]; then
        # Tag is a list of files
        if [ -d "$TARGET/$name" ]; then
            # Check if the source and target directores are the same
            # by checking one of the files
            f1="`ls "$TARGET/$name/"*.mp3 | head -1 `"
            f1n="`basename "$f1"`"
            if [ "$f1" -ef "$file/$f1n" ]; then
                # Exists and is the same
                continue
            fi
        fi

        if [ -e "$TARGET/$name" ]; then
            # Exists and is something else
            alt="`dirname "$file"`"
            alt="`basename "$alt"` - $name"
            name="$alt"
            if [ -e "$TARGET/$name" ]; then
                # The alternate already exists; we've done this folder already
                continue
            fi
        fi

        echo "$name"
        mkdir "$TARGET/$name"

        while read mp3; do
            ln -s "$file/$mp3" "$TARGET/$name/$mp3"
        done < "$tag"
    else
        # Tag is a zero-byte marker; link whole directory
        if [ -h "$TARGET/$name" ]; then
            # Check if the source and target directores are the same
            if [ "$TARGET/$name" -ef "$file" ]; then
                # Exists and is the same
                continue
            fi
        fi
        if [ -e "$TARGET/$name" ]; then
            # Exists and is something else
            alt="`dirname "$file"`"
            alt="`basename "$alt"` - $name"
            name="$alt"
            if [ -e "$TARGET/$name" ]; then
                # The alternate already exists; we've done this folder already
                continue
            fi
        fi

        echo "$name"
        ln -s "$file" "$TARGET/$name"
    fi
done
