#!/bin/bash

# BITS=16
FREQ=44100
CHANNELS=2
# UNSIGNED=''
BITRATE=128
ABR=''
ARTIST=''
ALBUM=''
ARTFOLD=''
TITLEARTFN=''
TEST=''

if [ "$1" = "" ]; then
    exec $0 '-?'
fi

while getopts "ab:f:c:ur:A:L:FTN?" opt; do
    case $opt in
        '?')
            echo -n "Convert a tracker module file to an MP3, using "
            echo "xmp and lame"
            echo
            echo "Usage: $0 \\"
            echo "  [-aFN] [-f freq] [-c chan]" \
                "[-r bitrate] [-A artist] [-L album] files..."
            echo
            echo "  -a: Encode using ABR (average bitrate)"
            echo "  -F: Take artist name from folder of original file"
            echo "  -N: Take artist from filename (in 'title - artist' form)"
            echo
            echo "  freq: Frequency to render in (default: $FREQ)"
            echo "  chan: Channels: 1 or 2 (default: $CHANNELS)"
            echo "  rate: MP3 bitrate to encode in (default: $BITRATE)"
            echo "  artist: Name of artist to place in ID3 tags"
            echo "  album: Name of album to place in ID3 tags"
            exit
            ;;
        # b)
        #     case "$OPTARG" in
        #         8) BITS=8;;
        #         16) BITS=16;;
        #         *)
        #             echo "Invalid value: $OPTARG"
        #             exit 1;
        #             ;;
        #     esac
        #     ;;

        f) FREQ="$OPTARG" ;;
        c) CHANNELS="$OPTARG" ;;
        # u) UNSIGNED=1 ;;
        r) BITRATE="$OPTARG" ;;
        a) ABR=1 ;;
        A) ARTIST="$OPTARG" ;;
        L) ALBUM="$OPTARG" ;;
        F) ARTFOLD=1 ;;
        N) TITLEARTFN=1 ;;
        T) TEST=1 ;;

        ?)
            echo ERROR
            exit 1
            ;;

    esac
done

# if [ $UNSIGNED ]; then
#     xunsigned='-u'
#     lsigned='--unsigned'
# else
#     lsigned='--signed'
# fi

if [ $ABR ]; then
    lbitrate="--abr $BITRATE"
else
    lbitrate="-b $BITRATE"
fi

shift $((OPTIND - 1))

echoq() {
    for word in "$@"; do
        if [ "$word" = "" -o "${word% *}" != "$word" ]; then
            echo -n "'$word' "
        else
            echo -n "$word "
        fi
    done
    echo
}


for file in "$@"; do
    name="`realpath "$file"`"
    name="${name%.*}"
    title="`basename "$name"`"

    if [ "$file" = "$name.mp3" ]; then
        echo "Already an MP3: $file"
    elif [ -e "$name.mp3" ]; then
        echo "Skipped, already converted: $file"
    elif ! openmpt123 --probe "$file" | grep -q Success; then
        echo "Skipped, not recognized by openmpt123: $file"
    else
        if [ $ARTFOLD ]; then
            dir="`dirname "$name"`"
            ARTIST="`basename "$dir"`"
        fi
        if [ $TITLEARTFN ]; then
            ARTIST="${title#* - }"
            title="${title% - *}"
        fi

        echo "$file"

        if [ $TEST ]; then
            TEST=echoq
        fi

        wav="`mktemp --suff .wav`"
        $TEST openmpt123 -o "$wav" --force \
            --samplerate "$FREQ" --channels "$CHANNELS" "$file" && \
            $TEST lame $lbitrate \
            --tt "$title" --ta "$ARTIST" --tl "$ALBUM" \
            "$wav" "$name.mp3" || rm -f "$name.mp3"
    fi
    rm -f "$wav"
done
