#!/usr/bin/python3

"""Decode an MP3 file with effects applied"""

import sys
from subprocess import Popen, check_output, PIPE

import mutagen

def parseTime( t ):
    sec = 0
    for i in t.split( ":" ): sec = sec * 60 + int( i or 0 )
    return sec

class settings:
    rate = 44010
    width = 16
    channels = 2
    fmt = "signed-integer"
    fx = ["compand", "0.3,1", "-90,-90,-70,-70,-60,-20,0,0", "-5", "0", "0.2"]

filename = sys.argv[1]

fileinfo = mutagen.File( filename )
length = int( fileinfo.info.length )

start = parseTime( fileinfo['TXXX:Start'][0] ) if 'TXXX:Start' in fileinfo else None
end = parseTime( fileinfo['TXXX:End'][0] ) if 'TXXX:End' in fileinfo else None
fadein = int( fileinfo['TXXX:FadeIn'][0] ) if 'TXXX:FadeIn' in fileinfo else None
fadeout = int( fileinfo['TXXX:FadeOut'][0] ) if 'TXXX:FadeOut' in fileinfo else None

args = ["madplay", 
        "-b", str( settings.width ),
        "-R", str( settings.rate ),
        "-S" if settings.channels == 2 else "-m"]

if start:
    args.extend( ['-s', str( start )] )
if end:
    args.extend( ['-t', str( end - (start or 0) )] )


args.extend( [
    "-o", "raw:-", 
    filename] )

decoder = Popen( args, stdout=PIPE )

args = ["sox",
        "-t", "raw", 
        "-r", str( settings.rate ),
        "-b", str( settings.width ),
        "-e", str( settings.fmt ),
        "-c", str( settings.channels ),
        "-",
        "-t", "raw", 
        "-r", str( settings.rate ),
        "-b", str( settings.width ),
        "-e", str( settings.fmt ),
        "-c", str( settings.channels ),
        "-"]

args.extend( settings.fx )

if fadein or fadeout:
    args.extend( ["fade", 'h', str( fadein or 0 )] )
    if fadeout:
        if end:
            time = end - (start or 0)
        else:
            time = length
        args.extend( [str( time ), str( fadeout )] )

print( args )

proc = Popen( args, stdin=decoder.stdout, stdout=PIPE )

args = ["play", 
        "-t", "raw", 
        "-r", str( settings.rate ),
        "-b", str( settings.width ),
        "-e", str( settings.fmt ),
        "-c", str( settings.channels ),
        "-"]

player = Popen( args, stdin=proc.stdout )

player.wait()

